import type { SelectMixedOption } from 'naive-ui/es/select/src/interface'

export function useMockOptions() {
  const localeOptions: SelectMixedOption[] = [
    { label: '中文', value: 'ZH_CN' },
    { label: '繁体中文', value: 'ZH_TW' },
    { label: 'English', value: 'EN' },
    { label: '日本語', value: 'JA_JP' },
    { label: 'Français', value: 'FR_FR' },
    { label: 'Deutsch', value: 'DE_DE' },
    { label: 'Italiano', value: 'IT_IT' },
    { label: 'Português (BR)', value: 'PT_BR' },
    { label: 'Português (PT)', value: 'PT_PT' },
    { label: 'Nederlands', value: 'NL_NL' },
    { label: 'العربية', value: 'AR_SA' },
    { label: 'Türkçe', value: 'TR_TR' },
    { label: 'فارسی', value: 'FA_IR' },
  ]

  const dataTypeOptions: SelectMixedOption[] = [
    { label: 'INTEGER', value: 'integer' },
    { label: 'BIGINT', value: 'bigint' },
    { label: 'FLOAT', value: 'float' },
    { label: 'DOUBLE', value: 'double' },
    { label: 'DECIMAL', value: 'decimal' },
    { label: 'BOOLEAN', value: 'boolean' },
    { label: 'VARCHAR', value: 'varchar' },
    { label: 'TEXT', value: 'text' },
    { label: 'DATE', value: 'date' },
    { label: 'DATETIME', value: 'datetime' },
    { label: 'TIMESTAMP', value: 'timestamp' },
    { label: 'UUID', value: 'uuid' },
  ]

  const generatorOptions: SelectMixedOption[] = [
    {
      type: 'group',
      label: '数字',
      key: 'g_numeric',
      children: [
        { label: '自动递增', value: 'auto_increment' },
        { label: '随机整数', value: 'random_int' },
        { label: '随机浮点数', value: 'random_float' },
        { label: '随机小数', value: 'random_decimal' },
        { label: '正态分布', value: 'normal' },
        { label: '对数正态', value: 'log_normal' },
        { label: '随机游走', value: 'random_walk' },
        { label: '数字格式', value: 'number_with_format' },
        { label: '单个数字', value: 'digit' },
      ],
    },
    {
      type: 'group',
      label: '人物信息',
      key: 'g_person',
      children: [
        { label: '姓名', value: 'name' },
        { label: '名', value: 'first_name' },
        { label: '姓', value: 'last_name' },
        { label: '姓名(带称谓)', value: 'name_with_title' },
        { label: '头衔', value: 'title' },
        { label: '姓名后缀', value: 'suffix' },
        { label: 'Email', value: 'email' },
        { label: 'Safe Email', value: 'safe_email' },
        { label: 'Free Email', value: 'free_email' },
        { label: 'Email Provider', value: 'free_email_provider' },
        { label: 'Domain Suffix', value: 'domain_suffix' },
        { label: 'Username', value: 'username' },
        { label: 'Password', value: 'password' },
        { label: 'Phone Number', value: 'phone_number' },
        { label: 'Phone (Digits)', value: 'cell_number' },
      ],
    },
    {
      type: 'group',
      label: '地址',
      key: 'g_address',
      children: [
        { label: '国家', value: 'country' },
        { label: '国家名', value: 'country_name' },
        { label: '国家代码', value: 'country_code' },
        { label: '城市', value: 'city' },
        { label: '城市前缀', value: 'city_prefix' },
        { label: '城市后缀', value: 'city_suffix' },
        { label: '州/省', value: 'state_name' },
        { label: '州缩写', value: 'state_abbr' },
        { label: '街道名', value: 'street_name' },
        { label: '街道后缀', value: 'street_suffix' },
        { label: '邮编', value: 'zip_code' },
        { label: '邮编(通用)', value: 'post_code' },
        { label: '楼号', value: 'building_number' },
        { label: '二级地址', value: 'secondary_address' },
        { label: '二级地址类型', value: 'secondary_address_type' },
        { label: '经度', value: 'latitude' },
        { label: '纬度', value: 'longitude' },
        { label: 'GeoHash', value: 'geohash' },
        { label: '时区', value: 'timezone' },
      ],
    },
    {
      type: 'group',
      label: '日期时间',
      key: 'g_datetime',
      children: [
        { label: '日期', value: 'date' },
        { label: '时间', value: 'time' },
        { label: '日期时间', value: 'datetime' },
        { label: '过去时间', value: 'datetime_before' },
        { label: '将来时间', value: 'datetime_after' },
        { label: '时间区间', value: 'datetime_between' },
        { label: '递增序列', value: 'sequential_date' },
        { label: '含缺失间隔', value: 'sequential_date_with_gaps' },
        { label: '持续时间', value: 'duration' },
      ],
    },
    {
      type: 'group',
      label: '商业',
      key: 'g_business',
      children: [
        { label: '公司名', value: 'company_name' },
        { label: '公司后缀', value: 'company_suffix' },
        { label: '职位', value: 'job_title' },
        { label: '行业', value: 'industry' },
        { label: '专业', value: 'profession' },
        { label: '职级', value: 'seniority' },
        { label: '领域', value: 'field' },
        { label: '岗位', value: 'position' },
        { label: '热词', value: 'buzzword' },
        { label: '热词(中)', value: 'buzzword_middle' },
        { label: '热词(尾)', value: 'buzzword_tail' },
        { label: '口号', value: 'catch_phrase' },
        { label: '币种代码', value: 'currency_code' },
        { label: '币种名', value: 'currency_name' },
        { label: '币种符号', value: 'currency_symbol' },
        { label: 'Credit Card No.', value: 'credit_card_number' },
        { label: 'BIC', value: 'bic' },
        { label: 'ISIN', value: 'isin' },
      ],
    },
    {
      type: 'group',
      label: '文本',
      key: 'g_text',
      children: [
        { label: '句子', value: 'sentence' },
        { label: '多句', value: 'sentences' },
        { label: '段落', value: 'paragraph' },
        { label: '多段落', value: 'paragraphs' },
        { label: '单词组', value: 'words' },
        { label: '单个单词', value: 'word' },
        { label: '正则', value: 'regex' },
        { label: '模板', value: 'template' },
        { label: 'Markdown 斜体', value: 'md_italic' },
        { label: 'Markdown 粗体', value: 'md_bold' },
        { label: 'Markdown 链接', value: 'md_link' },
        { label: 'Markdown 列表项', value: 'md_bullet' },
        { label: 'Markdown 列表', value: 'md_list' },
        { label: 'Markdown 引用(单)', value: 'md_blockquote_single' },
        { label: 'Markdown 引用(多)', value: 'md_blockquote_multi' },
        { label: 'Markdown 代码', value: 'md_code' },
        { label: 'Lorem 短语', value: 'bs' },
        { label: 'Lorem 动词', value: 'bs_verb' },
        { label: 'Lorem 形容词', value: 'bs_adj' },
        { label: 'Lorem 名词', value: 'bs_noun' },
      ],
    },
    {
      type: 'group',
      label: '网络 & 技术',
      key: 'g_tech',
      children: [
        { label: 'UUID v1', value: 'uuid_v1' },
        { label: 'UUID v3', value: 'uuid_v3' },
        { label: 'UUID v4', value: 'uuid_v4' },
        { label: 'UUID v5', value: 'uuid_v5' },
        { label: 'ULID', value: 'ferroid_ulid' },
        { label: 'Twitter ID', value: 'ferroid_twitter_id' },
        { label: 'Instagram ID', value: 'ferroid_instagram_id' },
        { label: 'Mastodon ID', value: 'ferroid_mastodon_id' },
        { label: 'Discord ID', value: 'ferroid_discord_id' },
        { label: 'URL', value: 'url' },
        { label: 'IP 地址', value: 'ip_address' },
        { label: 'IPv4', value: 'ipv4' },
        { label: 'IPv6', value: 'ipv6' },
        { label: 'IP 通用', value: 'ip' },
        { label: 'MAC 地址', value: 'mac_address' },
        { label: '用户代理', value: 'user_agent' },
        { label: 'MIME 类型', value: 'mime_type' },
        { label: 'SemVer', value: 'semver' },
        { label: 'SemVer(稳定)', value: 'semver_stable' },
        { label: 'SemVer(不稳定)', value: 'semver_unstable' },
        { label: '文件路径', value: 'file_path' },
        { label: '目录路径', value: 'dir_path' },
        { label: '图片 URL', value: 'image_url' },
        { label: '图片(种子)', value: 'image_url_with_seed' },
        { label: '图片(灰度)', value: 'image_url_grayscale' },
        { label: '图片(模糊)', value: 'image_url_blur' },
        { label: '图片(自定义)', value: 'image_url_custom' },
        { label: 'Hex 颜色', value: 'hex_color' },
        { label: 'RGB 颜色', value: 'rgb_color' },
        { label: 'RGBA 颜色', value: 'rgba_color' },
        { label: 'HSL 颜色', value: 'hsl_color' },
        { label: 'HSLA 颜色', value: 'hsla_color' },
        { label: '颜色通用', value: 'color' },
      ],
    },
    {
      type: 'group',
      label: '标记',
      key: 'g_misc',
      children: [
        { label: '文件名', value: 'file_name' },
        { label: '文件扩展名', value: 'file_extension' },
        { label: '常量', value: 'constant' },
        { label: '布尔值', value: 'boolean' },
        { label: 'ISBN', value: 'isbn' },
        { label: 'ISBN-10', value: 'isbn10' },
        { label: 'ISBN-13', value: 'isbn13' },
        { label: 'RFC 状态码', value: 'rfc_status' },
        { label: 'HTTP Status', value: 'valid_status' },
        { label: 'License Plate', value: 'licence_plate' },
        { label: 'Health Insurance', value: 'health_insurance' },
        { label: '外键约束', value: 'foreign_key' },
        { label: '序列循环', value: 'sequence' },
        { label: '加权随机', value: 'weighted' },
      ],
    },
  ]

  const formatExtMap: Record<string, { ext: string; label: string }> = {
    csv: { ext: 'csv', label: 'CSV' },
    xlsx: { ext: 'xlsx', label: 'Excel' },
    parquet: { ext: 'parquet', label: 'Parquet' },
    sql: { ext: 'sql', label: 'SQL' },
  }

  const scratchpadOptions = [
    { label: 'CSV → 草稿箱', key: 'Csv' },
    { label: 'XLSX → 草稿箱', key: 'Xlsx' },
    { label: 'Parquet → 草稿箱', key: 'Parquet' },
    { label: 'SQL INSERT → 草稿箱', key: 'SqlInsert' },
  ]

  return {
    localeOptions,
    dataTypeOptions,
    generatorOptions,
    formatExtMap,
    scratchpadOptions,
  }
}